# Generated by Django 5.1.1 on 2025-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='username')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('new_password', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=4)),
                ('is_verified', models.BooleanField(default=False)),
                ('reset_pass', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
