# Generated by Django 5.1.1 on 2025-03-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_package', '0002_alter_package_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='package',
            name='password',
        ),
    ]
